#include "ros2_tui_launcher/profile_generator.hpp"

#include "ros2_tui_launcher/host_process_lookup.hpp"

#include <yaml-cpp/yaml.h>

#include <algorithm>
#include <chrono>
#include <ctime>
#include <iomanip>
#include <ostream>
#include <sstream>
#include <unordered_map>

namespace rtl {

namespace {
constexpr const char* kFillPlaceholder = "<FILL>";

bool startsWithAny(const std::string& s, const std::unordered_set<std::string>& prefixes) {
    for (const auto& p : prefixes) {
        if (s.rfind(p, 0) == 0) return true;
    }
    return false;
}

std::string defaultProfileName() {
    auto now = std::chrono::system_clock::now();
    auto t = std::chrono::system_clock::to_time_t(now);
    std::ostringstream ss;
    ss << "generated-" << std::put_time(std::localtime(&t), "%Y%m%d-%H%M%S");
    return ss.str();
}

std::string nodeEntryName(const GraphNode& gn) {
    if (!gn.ns.empty() && gn.ns != "/") {
        return gn.ns + "/" + gn.name;
    }
    return gn.name;
}
}  // namespace

LaunchProfile generateProfile(const GraphSnapshot& snap,
                              const GenerateOptions& opts,
                              TopicMonitor* topic_monitor) {
    LaunchProfile profile;
    profile.name = opts.profile_name.empty() ? defaultProfileName() : opts.profile_name;
    profile.description = "Scaffolded from a live ROS 2 graph snapshot. "
                          "Replace <FILL> placeholders before launching.";

    std::vector<HostProcInfo> procs;
    if (opts.host_lookup) {
        procs = scanRos2HostProcesses();
    }

    if (opts.include_nodes) {
        for (const auto& gn : snap.nodes) {
            if (startsWithAny(gn.name, opts.exclude_node_names)) continue;

            LaunchEntry entry;
            entry.name = nodeEntryName(gn);
            entry.package = kFillPlaceholder;
            entry.executable = kFillPlaceholder;

            if (opts.host_lookup) {
                const auto* p = matchHostProcess(gn.name, entry.name, procs);
                if (p) {
                    if (!p->package.empty())    entry.package = p->package;
                    if (!p->executable.empty()) entry.executable = p->executable;
                }
            }

            entry.autostart = false;
            entry.restart_policy = "on-failure";
            profile.entries.push_back(std::move(entry));
        }
    }

    std::unordered_map<std::string, double> measured_hz;
    if (topic_monitor) {
        for (const auto& ti : topic_monitor->snapshot()) {
            measured_hz[ti.name] = ti.hz;
        }
    }

    if (opts.include_topics) {
        for (const auto& gt : snap.topics) {
            if (opts.exclude_topic_names.count(gt.name)) continue;
            if (gt.publisher_nodes.empty()) continue;

            MonitoredTopic mt;
            mt.topic = gt.name;
            auto it = measured_hz.find(gt.name);
            mt.expected_hz = (it != measured_hz.end()) ? it->second : 0.0;
            profile.monitored_topics.push_back(std::move(mt));
        }
    }

    return profile;
}

void writeProfileYaml(const LaunchProfile& profile, std::ostream& out) {
    YAML::Emitter e;
    e << YAML::Comment(
        "Generated by `rtl config generate`. Fill in <FILL> placeholders "
        "(package + executable) before launching this profile.");
    e << YAML::BeginMap;
    e << YAML::Key << "name" << YAML::Value << profile.name;
    e << YAML::Key << "description" << YAML::Value << profile.description;

    if (!profile.entries.empty()) {
        e << YAML::Key << "launch" << YAML::Value << YAML::BeginSeq;
        for (const auto& entry : profile.entries) {
            e << YAML::BeginMap;
            e << YAML::Key << "name" << YAML::Value << entry.name;
            e << YAML::Key << "package" << YAML::Value << entry.package;
            if (entry.package == "<FILL>") {
                e << YAML::Comment("ros2 pkg list | grep <something>");
            }
            e << YAML::Key << "executable" << YAML::Value << entry.executable;
            if (entry.executable == "<FILL>") {
                e << YAML::Comment("ros2 pkg executables <package>");
            }
            e << YAML::Key << "autostart" << YAML::Value << entry.autostart;
            e << YAML::Key << "restart_policy" << YAML::Value << entry.restart_policy;
            e << YAML::EndMap;
        }
        e << YAML::EndSeq;
    }

    if (!profile.monitored_topics.empty()) {
        e << YAML::Key << "monitor" << YAML::Value << YAML::BeginMap;
        e << YAML::Key << "topics" << YAML::Value << YAML::BeginSeq;
        for (const auto& mt : profile.monitored_topics) {
            e << YAML::BeginMap;
            e << YAML::Key << "name" << YAML::Value << mt.topic;
            e << YAML::Key << "expected_hz" << YAML::Value << mt.expected_hz;
            e << YAML::EndMap;
        }
        e << YAML::EndSeq;
        e << YAML::Key << "hz_rate" << YAML::Value << profile.topic_hz_rate;
        e << YAML::EndMap;
    }

    e << YAML::EndMap;

    out << e.c_str() << "\n";
}

}  // namespace rtl
